### ISSUE TITLE
如何控制加载顺序？

### ISSUE THREAD

**Issue by naive1024** [dishait/vite-plugin-use-modules#1]
有配置，加载优先级嘛？

**Comment by markthree** [comment]
@naive1024 靓仔你好，无顺序哦。具体实现原理可见 👉 [glob-import](https://vitejs.cn/guide/features.html#glob-import)。当然，欢迎 `pr` 哦

**Comment by markthree** [comment]
@naive1024 靓仔你好，现在你能够通过数字前缀文件名来控制加载的优先级别了。
例如 `1.foo.ts` 比 `2.bar.ts`... 以此类推
