### ISSUE TITLE
是否可以排除部分文件？

### ISSUE THREAD

**Issue by BryanAdamss** [dishait/vite-plugin-use-modules#2]
看源码里直接读取了target下的js/ts，可考虑支持直接传入glob用来排除部分文件
```js
	const t = `'${target}/*.[tj]s'`
```

**Comment by markthree** [comment]
@BryanAdamss 已支持，具体可见 [eca1e](https://github.com/dishait/vite-plugin-use-modules/commit/eca1ef21e3dcfff5693b7b0cd0db0a31521145ea) 和 [f556d](https://github.com/dishait/vite-plugin-use-modules/commit/f556d4ed7205a17876aaf5f58529af68f316754c)
